version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
